[versions]
assertj = "3.27.7"
jspecify = "1.0.0"
junit = "6.0.2"
nmcp = "1.4.4"
spotless = "8.2.1"

[plugins]
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

# direct versions
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
