[versions]
assertj = "3.27.7"
errorprone = "2.47.0"
errorprone-plugin = "5.0.0"
jspecify = "1.0.0"
junit = "6.0.3"
nmcp = "1.4.4"
nullaway = "0.13.1"
spotless = "8.2.1"

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

# direct versions
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

# versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
