name: Gradle Publish [release]

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"    # pattern for v1.2.3
      - "v[0-9]*.[0-9]*.[0-9]*-*"  # pattern for v1.2.3-suffix

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Publish Release
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          PUBLISHING_USERNAME: ${{ secrets.PUBLISHING_USERNAME }}
          PUBLISHING_PASSWORD: ${{ secrets.PUBLISHING_PASSWORD }}
          GRADLE_OPTS: >-
            -Dorg.gradle.configuration-cache=false
            -Dorg.gradle.daemon=false
            -Dorg.gradle.parallel=false
            -Dorg.gradle.workers.max=1
        run: |
          VERSION="${GITHUB_REF_NAME#v}"  # removes leading 'v' from tag name
          echo "::notice::publishing version $VERSION"
          ./gradlew -Pversion="$VERSION" -Psign publishAllPublicationsToCentralPortal
